//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SitioWeb.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Service.ServiceSoap")]
    public interface ServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strNombre del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        SitioWeb.Service.testResponse test(SitioWeb.Service.testRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/test", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.Service.testResponse> testAsync(SitioWeb.Service.testRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strBody del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        SitioWeb.Service.LoginResponse Login(SitioWeb.Service.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.Service.LoginResponse> LoginAsync(SitioWeb.Service.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strBody del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCuenta", ReplyAction="*")]
        SitioWeb.Service.CrearCuentaResponse CrearCuenta(SitioWeb.Service.CrearCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CrearCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.Service.CrearCuentaResponse> CrearCuentaAsync(SitioWeb.Service.CrearCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCuenta", ReplyAction="*")]
        int EliminarCuenta(int intCliente);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/EliminarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<int> EliminarCuentaAsync(int intCliente);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento strBody del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCuenta", ReplyAction="*")]
        SitioWeb.Service.ActualizarCuentaResponse ActualizarCuenta(SitioWeb.Service.ActualizarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ActualizarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.Service.ActualizarCuentaResponse> ActualizarCuentaAsync(SitioWeb.Service.ActualizarCuentaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento VisualizarCuentaResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizarCuenta", ReplyAction="*")]
        SitioWeb.Service.VisualizarCuentaResponse VisualizarCuenta(SitioWeb.Service.VisualizarCuentaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VisualizarCuenta", ReplyAction="*")]
        System.Threading.Tasks.Task<SitioWeb.Service.VisualizarCuentaResponse> VisualizarCuentaAsync(SitioWeb.Service.VisualizarCuentaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="test", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.testRequestBody Body;
        
        public testRequest() {
        }
        
        public testRequest(SitioWeb.Service.testRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strNombre;
        
        public testRequestBody() {
        }
        
        public testRequestBody(string strNombre) {
            this.strNombre = strNombre;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class testResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="testResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.testResponseBody Body;
        
        public testResponse() {
        }
        
        public testResponse(SitioWeb.Service.testResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class testResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string testResult;
        
        public testResponseBody() {
        }
        
        public testResponseBody(string testResult) {
            this.testResult = testResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(SitioWeb.Service.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBody;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string strBody) {
            this.strBody = strBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(SitioWeb.Service.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCuenta", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.CrearCuentaRequestBody Body;
        
        public CrearCuentaRequest() {
        }
        
        public CrearCuentaRequest(SitioWeb.Service.CrearCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBody;
        
        public CrearCuentaRequestBody() {
        }
        
        public CrearCuentaRequestBody(string strBody) {
            this.strBody = strBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CrearCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CrearCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.CrearCuentaResponseBody Body;
        
        public CrearCuentaResponse() {
        }
        
        public CrearCuentaResponse(SitioWeb.Service.CrearCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CrearCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CrearCuentaResult;
        
        public CrearCuentaResponseBody() {
        }
        
        public CrearCuentaResponseBody(int CrearCuentaResult) {
            this.CrearCuentaResult = CrearCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.ActualizarCuentaRequestBody Body;
        
        public ActualizarCuentaRequest() {
        }
        
        public ActualizarCuentaRequest(SitioWeb.Service.ActualizarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strBody;
        
        public ActualizarCuentaRequestBody() {
        }
        
        public ActualizarCuentaRequestBody(string strBody) {
            this.strBody = strBody;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ActualizarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ActualizarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.ActualizarCuentaResponseBody Body;
        
        public ActualizarCuentaResponse() {
        }
        
        public ActualizarCuentaResponse(SitioWeb.Service.ActualizarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ActualizarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int ActualizarCuentaResult;
        
        public ActualizarCuentaResponseBody() {
        }
        
        public ActualizarCuentaResponseBody(int ActualizarCuentaResult) {
            this.ActualizarCuentaResult = ActualizarCuentaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VisualizarCuentaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VisualizarCuenta", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.VisualizarCuentaRequestBody Body;
        
        public VisualizarCuentaRequest() {
        }
        
        public VisualizarCuentaRequest(SitioWeb.Service.VisualizarCuentaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VisualizarCuentaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int intCliente;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int intOpcion;
        
        public VisualizarCuentaRequestBody() {
        }
        
        public VisualizarCuentaRequestBody(int intCliente, int intOpcion) {
            this.intCliente = intCliente;
            this.intOpcion = intOpcion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VisualizarCuentaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VisualizarCuentaResponse", Namespace="http://tempuri.org/", Order=0)]
        public SitioWeb.Service.VisualizarCuentaResponseBody Body;
        
        public VisualizarCuentaResponse() {
        }
        
        public VisualizarCuentaResponse(SitioWeb.Service.VisualizarCuentaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class VisualizarCuentaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string VisualizarCuentaResult;
        
        public VisualizarCuentaResponseBody() {
        }
        
        public VisualizarCuentaResponseBody(string VisualizarCuentaResult) {
            this.VisualizarCuentaResult = VisualizarCuentaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceSoapChannel : SitioWeb.Service.ServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<SitioWeb.Service.ServiceSoap>, SitioWeb.Service.ServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.Service.testResponse SitioWeb.Service.ServiceSoap.test(SitioWeb.Service.testRequest request) {
            return base.Channel.test(request);
        }
        
        public string test(string strNombre) {
            SitioWeb.Service.testRequest inValue = new SitioWeb.Service.testRequest();
            inValue.Body = new SitioWeb.Service.testRequestBody();
            inValue.Body.strNombre = strNombre;
            SitioWeb.Service.testResponse retVal = ((SitioWeb.Service.ServiceSoap)(this)).test(inValue);
            return retVal.Body.testResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.Service.testResponse> SitioWeb.Service.ServiceSoap.testAsync(SitioWeb.Service.testRequest request) {
            return base.Channel.testAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.Service.testResponse> testAsync(string strNombre) {
            SitioWeb.Service.testRequest inValue = new SitioWeb.Service.testRequest();
            inValue.Body = new SitioWeb.Service.testRequestBody();
            inValue.Body.strNombre = strNombre;
            return ((SitioWeb.Service.ServiceSoap)(this)).testAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.Service.LoginResponse SitioWeb.Service.ServiceSoap.Login(SitioWeb.Service.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string strBody) {
            SitioWeb.Service.LoginRequest inValue = new SitioWeb.Service.LoginRequest();
            inValue.Body = new SitioWeb.Service.LoginRequestBody();
            inValue.Body.strBody = strBody;
            SitioWeb.Service.LoginResponse retVal = ((SitioWeb.Service.ServiceSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.Service.LoginResponse> SitioWeb.Service.ServiceSoap.LoginAsync(SitioWeb.Service.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.Service.LoginResponse> LoginAsync(string strBody) {
            SitioWeb.Service.LoginRequest inValue = new SitioWeb.Service.LoginRequest();
            inValue.Body = new SitioWeb.Service.LoginRequestBody();
            inValue.Body.strBody = strBody;
            return ((SitioWeb.Service.ServiceSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.Service.CrearCuentaResponse SitioWeb.Service.ServiceSoap.CrearCuenta(SitioWeb.Service.CrearCuentaRequest request) {
            return base.Channel.CrearCuenta(request);
        }
        
        public int CrearCuenta(string strBody) {
            SitioWeb.Service.CrearCuentaRequest inValue = new SitioWeb.Service.CrearCuentaRequest();
            inValue.Body = new SitioWeb.Service.CrearCuentaRequestBody();
            inValue.Body.strBody = strBody;
            SitioWeb.Service.CrearCuentaResponse retVal = ((SitioWeb.Service.ServiceSoap)(this)).CrearCuenta(inValue);
            return retVal.Body.CrearCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.Service.CrearCuentaResponse> SitioWeb.Service.ServiceSoap.CrearCuentaAsync(SitioWeb.Service.CrearCuentaRequest request) {
            return base.Channel.CrearCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.Service.CrearCuentaResponse> CrearCuentaAsync(string strBody) {
            SitioWeb.Service.CrearCuentaRequest inValue = new SitioWeb.Service.CrearCuentaRequest();
            inValue.Body = new SitioWeb.Service.CrearCuentaRequestBody();
            inValue.Body.strBody = strBody;
            return ((SitioWeb.Service.ServiceSoap)(this)).CrearCuentaAsync(inValue);
        }
        
        public int EliminarCuenta(int intCliente) {
            return base.Channel.EliminarCuenta(intCliente);
        }
        
        public System.Threading.Tasks.Task<int> EliminarCuentaAsync(int intCliente) {
            return base.Channel.EliminarCuentaAsync(intCliente);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.Service.ActualizarCuentaResponse SitioWeb.Service.ServiceSoap.ActualizarCuenta(SitioWeb.Service.ActualizarCuentaRequest request) {
            return base.Channel.ActualizarCuenta(request);
        }
        
        public int ActualizarCuenta(string strBody) {
            SitioWeb.Service.ActualizarCuentaRequest inValue = new SitioWeb.Service.ActualizarCuentaRequest();
            inValue.Body = new SitioWeb.Service.ActualizarCuentaRequestBody();
            inValue.Body.strBody = strBody;
            SitioWeb.Service.ActualizarCuentaResponse retVal = ((SitioWeb.Service.ServiceSoap)(this)).ActualizarCuenta(inValue);
            return retVal.Body.ActualizarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.Service.ActualizarCuentaResponse> SitioWeb.Service.ServiceSoap.ActualizarCuentaAsync(SitioWeb.Service.ActualizarCuentaRequest request) {
            return base.Channel.ActualizarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.Service.ActualizarCuentaResponse> ActualizarCuentaAsync(string strBody) {
            SitioWeb.Service.ActualizarCuentaRequest inValue = new SitioWeb.Service.ActualizarCuentaRequest();
            inValue.Body = new SitioWeb.Service.ActualizarCuentaRequestBody();
            inValue.Body.strBody = strBody;
            return ((SitioWeb.Service.ServiceSoap)(this)).ActualizarCuentaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SitioWeb.Service.VisualizarCuentaResponse SitioWeb.Service.ServiceSoap.VisualizarCuenta(SitioWeb.Service.VisualizarCuentaRequest request) {
            return base.Channel.VisualizarCuenta(request);
        }
        
        public string VisualizarCuenta(int intCliente, int intOpcion) {
            SitioWeb.Service.VisualizarCuentaRequest inValue = new SitioWeb.Service.VisualizarCuentaRequest();
            inValue.Body = new SitioWeb.Service.VisualizarCuentaRequestBody();
            inValue.Body.intCliente = intCliente;
            inValue.Body.intOpcion = intOpcion;
            SitioWeb.Service.VisualizarCuentaResponse retVal = ((SitioWeb.Service.ServiceSoap)(this)).VisualizarCuenta(inValue);
            return retVal.Body.VisualizarCuentaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SitioWeb.Service.VisualizarCuentaResponse> SitioWeb.Service.ServiceSoap.VisualizarCuentaAsync(SitioWeb.Service.VisualizarCuentaRequest request) {
            return base.Channel.VisualizarCuentaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SitioWeb.Service.VisualizarCuentaResponse> VisualizarCuentaAsync(int intCliente, int intOpcion) {
            SitioWeb.Service.VisualizarCuentaRequest inValue = new SitioWeb.Service.VisualizarCuentaRequest();
            inValue.Body = new SitioWeb.Service.VisualizarCuentaRequestBody();
            inValue.Body.intCliente = intCliente;
            inValue.Body.intOpcion = intOpcion;
            return ((SitioWeb.Service.ServiceSoap)(this)).VisualizarCuentaAsync(inValue);
        }
    }
}
